# Generated by Django 4.0.5 on 2022-06-25 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_foods_catogory_delete_catogory'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='Pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 6, 25, 10, 19, 55, 695278, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
