# Generated by Django 4.0.5 on 2022-06-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='order', to='restaurant.foods'),
        ),
        migrations.AddField(
            model_name='foods',
            name='category',
            field=models.ManyToManyField(related_name='item', to='restaurant.category'),
        ),
    ]
